version: '3.5'

services:
  admin.web:
    build: .
    container_name: shop-admin-web
    ports:
      - 6002:80
    volumes:
      - ../dist:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    restart: always