version: '3.4'

services:
  redis:
    image: redis:6
    container_name: demo-shop-redis
    ports:
      - "6379:6379"
    volumes:
      - /home/demo-shop/redis/data:/data
    restart: always
    networks:
      - demo-shop-net
    deploy:
      resources:
        limits:
          memory: 1GB
    command: redis-server --appendonly yes --requirepass qGmNTfPtbQYMX6Qz

  mysql:
    image: mysql:5.7
    container_name: demo-shop-mysql
    ports:
      - "3306:3306"
    volumes:
      - /home/demo-shop/mysql:/var/lib/mysql
    restart: always
    networks:
      - demo-shop-net
    deploy:
      resources:
        limits:
          memory: 1GB
    environment:
      - MYSQL_ROOT_PASSWORD=nzuxZ3Wf4aqfWfGz
      - MYSQL_DATABASE=module-shop
      - TZ=Asia/Shanghai
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  rabbitmq:
    image: rabbitmq:3-management
    container_name: demo-shop-mq
    ports:
      - "5672:5672"
      - "15671:15672"
    volumes:
      - /home/demo-shop/rabbitmq:/var/lib/rabbitmq
    restart: always
    networks:
      - demo-shop-net
    deploy:
      resources:
        limits:
          memory: 1GB
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=7BKq9vFAqz6Puzjj

# docker network create demo-shop-net
networks:
  demo-shop-net:
    external: true